version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always

    environment:
      MSSQL_SA_PASSWORD: Admin123
      ACCEPT_EULA: Y
      MSSQL_DATA_DIR: /var/opt/sqlserver/data
      MSSQL_LOG_DIR: /var/opt/sqlserver/log
      MSSQL_BACKUP_DIR: /var/opt/sqlserver/backup

    volumes:
      - ./data:/var/opt/sqlserver/data
      - ./logs:/var/opt/sqlserver/log
      - ./backup:/var/opt/sqlserver/backup

    ports:
      - 1433:1433