version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.10.1
    restart: always

    environment: 
      - discovery.type=single-node

    volumes:
      - ./data:/usr/share/elasticsearch/data

    ports:
      - 9200:9200
      - 9300:9300
