version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    
    environment:
      MYSQL_ROOT_PASSWORD: Admin123

    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql

    ports:
      - 3306:3306